### ISSUE TITLE
Interface for .NET languages

### ISSUE THREAD

**Issue by burkenyo** [Cantera/enhancements#156]
**Abstract**

An interface will be created to provide access to Cantera through programming languages in the .NET ecosystem. The interface will be available as a Nuget package, allowing users to integrate Cantera directly into their project using familiar paradigms. 

**Motivation**

With the turn towards open-source and cross-platform that begun with .NET Core, coupled with crucial investments in the runtime and libraries to allow high-performance code, there is increasing interest in the community in using .NET for scientific computing.

In addition, there is a desire to extend Cantera to other languages such as Julia, using the C-interface for interop with the native Cantera library. The work on the .NET interface will take a first pass at implementing a source generator to scaffold code from the C-interface, as decscribed in https://github.com/Cantera/enhancements/issues/39.

**Description**

[TBD]

The initial version will support .NET Standard 2.0 (with the addition of nullable reference type attributes and memory types provided by Nuget packages) and .NET 6. This means the APIs not present in .NET Standard 2.0 (or provided by those two Nuget packages) will not be used.
String comparison in the C# layer will be performed with `StringComparer.OrdinalIgnoreCase` or ` StringComparison.OrdinalIgnoreCase`

**Tasks**

- [x] Initial commit with an example
- [ ] Hook build system up to scons
- [x] Integrate with CI

More tasks TBD re: mapping more and more functionality from CLib

- [ ] Develop Nuget packaging strategy for core library
- [ ] Develop Nuget packaging strategy for examples

TBD: develop Conda packaging strategy? 

**References**

https://github.com/burkenyo/cantera/tree/dotnet-interface

**Comment by burkenyo** [comment]
Hi, I’ve created this stub issue so that I have the number. I will flush it out soon.

**Comment by ischoegl** [comment]
One interesting factoid I just found (while trying to debug CMake for Cantera's standard C++ samples, where it generates `.sln` and `.vcxproj` files, among others) is that C# projects are supported by CMake as well (see [SO discussion](https://stackoverflow.com/questions/2074144/generate-c-sharp-project-using-cmake)). *(PS: since support may be limited to Windows, it may not be that interesting after all)*

**Comment by ischoegl** [comment]
@burkenyo ... linking back some PRs and discussions relevant to .NET, as this issue is [referenced from the Cantera documentation](https://cantera.org/dev/dotnet/index.html):

- Cantera/cantera#1596 
- Cantera/cantera#1888 (switch to generated CLib)
- Cantera/cantera#1894
- Cantera/cantera#1897 (changes in `sourcegen`)
